In [2]:
print("hello")


hello


In [3]:
import pandas as pd
a=pd.read_csv("Advertising.csv")
print(a)
a.head()



     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]


Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
a.shape

(200, 5)

In [6]:
a.describe() #decriptive analysis of each column

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [9]:
a.isnull().sum() #gives all the null values


Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [11]:
a.columns

Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [12]:
x=a[['TV','Radio','Newspaper']]
y=a[["Sales"]]

In [13]:
print(x)
print(y)

        TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]
     Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]


In [14]:
#training
#train & test split
#70%-80% training
#20-30% testing

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [17]:
print(x_train.shape,"Training data size for x")
print(x_test.shape,"Testing data size for x")
print(y_train.shape,"Training data size for y")
print(y_test.shape,"Testing data size for y")


(160, 3) Training data size for x
(40, 3) Testing data size for x
(160, 1) Training data size for y
(40, 1) Testing data size for y


In [18]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
model=lm.fit(x_train,y_train)

In [20]:
model.coef_

array([[ 0.04655612,  0.19147962, -0.00771804]])

In [21]:
model.intercept_

array([3.0645296])

In [22]:
#y=b0+b1x1+b2x2+b3x3
b0=3.0645296
b1=0.04655612
b2=0.19147962
b3=-0.00771804
y=b0+b1* 17.2 + b2* 45.86 + b3* 69.3
print(y)

12.1116900652


In [23]:
y_pred=model.predict(x_test)
print(y_pred)

[[15.23050545]
 [12.85594056]
 [ 8.64763895]
 [12.5531825 ]
 [12.4584465 ]
 [10.32597888]
 [10.48210313]
 [17.31785807]
 [ 8.13542196]
 [17.40169484]
 [16.80434781]
 [20.87993486]
 [17.26362163]
 [11.65229396]
 [21.35392214]
 [15.57330936]
 [18.27734558]
 [15.82381156]
 [13.96853603]
 [ 7.64546305]
 [15.32507981]
 [23.83857656]
 [19.25711333]
 [15.4001925 ]
 [ 8.05071646]
 [20.6867198 ]
 [14.24712941]
 [ 7.70590324]
 [12.21024794]
 [14.710966  ]
 [18.28072432]
 [ 9.89070276]
 [ 9.926771  ]
 [14.49504949]
 [ 4.49142693]
 [ 9.93038082]
 [15.50458504]
 [20.88688995]
 [15.37096361]
 [ 6.54319178]]


In [24]:
new_df=pd.DataFrame()
new_df=x_test
new_df['actual sales']=y_test
new_df['predicted sales']=y_pred
print(new_df)

        TV  Radio  Newspaper  actual sales  predicted sales
26   142.9   29.3       12.6          15.0        15.230505
115   75.1   35.0       52.7          12.6        12.855941
132    8.4   27.2        2.1           5.7         8.647639
179  165.6   10.0       17.6          12.6        12.553182
148   38.0   40.3       11.9          10.9        12.458447
158   11.7   36.9       45.2           7.3        10.325979
72    26.8   33.0       19.3           8.8        10.482103
35   290.7    4.1        8.5          12.8        17.317858
49    66.9   11.7       36.8           9.7         8.135422
41   177.0   33.4       38.7          17.1        17.401695
194  149.7   35.6        6.0          17.3        16.804348
137  273.7   28.9       59.7          20.8        20.879935
27   240.1   16.7       22.9          15.9        17.263622
136   25.6   39.0        9.3           9.5        11.652294
69   216.8   43.9       27.2          22.3        21.353922
146  240.1    7.3        8.7          13

In [25]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np
r2=r2_score(y_test,y_pred)
print("R-squared:",r2)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
print("RMSE:",rmse)


R-squared: 0.8444710517198928
RMSE: 1.8060644445826652
